### ISSUE TITLE
Maze solver example throws an error

### ISSUE THREAD

**Issue by levitabris** [JuliaDynamics/AgentsExampleZoo.jl#13]
Running the `maze.jl` file in the `docs/examples` directory gives the following error:
```
ERROR: LoadError: promotion of types Int64 and FixedPointNumbers.N0f8 failed to change any arguments
Stacktrace:
  [1] error(::String, ::String, ::String)
    @ Base ./error.jl:42
  [2] sametype_error(input::Tuple{Int64, FixedPointNumbers.N0f8})
    @ Base ./promotion.jl:374
  [3] not_sametype(x::Tuple{Int64, FixedPointNumbers.N0f8}, y::Tuple{Int64, FixedPointNumbers.N0f8})
    @ Base ./promotion.jl:368
  [4] promote
    @ ./promotion.jl:351 [inlined]
  [5] <(x::Int64, y::FixedPointNumbers.N0f8)
    @ Base ./promotion.jl:419
  [6] >(x::FixedPointNumbers.N0f8, y::Int64)
    @ Base ./operators.jl:378
  [7] (::var"#1#2")(x::ColorTypes.RGBX{FixedPointNumbers.N0f8})
    @ Main ~/Downloads/AgentsExampleZoo.jl-main/docs/examples/maze.jl:22
  [8] iterate
    @ ./generator.jl:47 [inlined]
  [9] _collect
    @ ./array.jl:744 [inlined]
 [10] collect_similar(cont::Matrix{ColorTypes.RGBX{FixedPointNumbers.N0f8}}, itr::Base.Generator{Matrix{ColorTypes.RGBX{FixedPointNumbers.N0f8}}, var"#1#2"})
    @ Base ./array.jl:653
 [11] map(f::Function, A::Matrix{ColorTypes.RGBX{FixedPointNumbers.N0f8}})
    @ Base ./abstractarray.jl:2867
 [12] initalize_model(map_url::String)
    @ Main ~/Downloads/AgentsExampleZoo.jl-main/docs/examples/maze.jl:22
 [13] top-level scope
    @ ~/Downloads/AgentsExampleZoo.jl-main/docs/examples/maze.jl:46
in expression starting at /Users/weili/Downloads/AgentsExampleZoo.jl-main/docs/examples/maze.jl:46
```

**Comment by Datseris** [comment]
what's the full versions of packages you used? try updating and running again.

**Comment by levitabris** [comment]
Here is my `st` output:

```
(@v1.7) pkg> st
      Status `~/.julia/environments/v1.7/Project.toml`
  [46ada45e] Agents v5.3.0
  [071ae1c0] DiffEqGPU v1.16.0
  [0c46a032] DifferentialEquations v7.1.0
  [5789e2e9] FileIO v1.15.0
  [7073ff75] IJulia v1.23.3
  [6218d12a] ImageMagick v1.2.2
  [961ee093] ModelingToolkit v8.7.0
  [c3e4b0f8] Pluto v0.19.1
  [dca85d43] QuartzImageIO v0.7.4
  [6f49c342] RCall v0.13.13
  [fd094767] Suppressor v0.2.1
```

**Comment by Datseris** [comment]
try updating and running again. AgentsExampleZoo always operates on latest stable Agents.jl version.

**Comment by AayushSabharwal** [comment]
If updating all packages doesn't fix this, I have an idea for why it might be erroring, but it will take some investigation. Also might want to try changing the function in the `map` to `x -> x.r > 0.0`.

I'd also suggest using different environments for different projects with `]activate .` and not adding everything to the global environment. It's one of the reasons Julia's package manager is so amazing, and often prevents headaches.

**Comment by levitabris** [comment]
> 

Tried both. But it still didn't work. Thank you anyway. Appreciated it!

**Comment by AayushSabharwal** [comment]
Does `x -> Float64(x.r) > 0.0` work?

**Comment by levitabris** [comment]
> If updating all packages doesn't fix this, I have an idea for why it might be erroring, but it will take some investigation. Also might want to try changing the function in the `map` to `x -> x.r > 0.0`.
> 
> I'd also suggest using different environments for different projects with `]activate .` and not adding everything to the global environment. It's one of the reasons Julia's package manager is so amazing, and often prevents headaches.

Tried both. Still didn't work. Thank you both anyway. Appreciated it.

**Comment by levitabris** [comment]
> Does `x -> Float64(x.r) > 0.0` work?

I don't think so. See below:
```
ERROR: LoadError: MethodError: no method matching Float64(::FixedPointNumbers.N0f8)
```

**Comment by AayushSabharwal** [comment]
What version of FixedPointNumbers do you have?

**Comment by levitabris** [comment]
> What version of FixedPointNumbers do you have?

Like this?
```
(AgentsExampleZoo) pkg> st FixedPointNumbers
     Project AgentsExampleZoo v0.1.0
      Status `~/Downloads/AgentsExampleZoo.jl-main/Project.toml` (empty project)
```

**Comment by Datseris** [comment]
Use `-m` to get the version, `st -m FixedPointNumbers`. It will also help you to have a look at the docs of Julias package manager (it is really amazing, will make your workflow so much faster) https://pkgdocs.julialang.org/v1/  and DrWatson for making managing projects easier https://juliadynamics.github.io/DrWatson.jl/dev/

**Comment by levitabris** [comment]
> Use `-m` to get the version, `st -m FixedPointNumbers`. It will also help you to have a look at the docs of Julias package manager (it is really amazing, will make your workflow so much faster) https://pkgdocs.julialang.org/v1/ and DrWatson for making managing projects easier https://juliadynamics.github.io/DrWatson.jl/dev/

The `FixedPointNumbers` is not installed by calling `instantiate` in the project. So I manually added the following version:
```
(AgentsExampleZoo) pkg> st -m FixedPointNumbers
     Project AgentsExampleZoo v0.1.0
      Status `~/Downloads/AgentsExampleZoo.jl-main/Manifest.toml`
  [53c48c17] FixedPointNumbers v0.8.4
```
The problem still persists. The following variations are tried with no good result:
`x -> Float64(x.r) > 0.0 `,`x -> float64(x.r) > 0.0`, `x -> x.r > 0.0`
