### ISSUE TITLE
Predator-Prey example not found

### ISSUE THREAD

**Issue by neosanma** [JuliaDynamics/AgentsExampleZoo.jl#15]
Hello, 
when trying to access the Predator-prey example in the "Mixed Models" section of the repo's website (https://juliadynamics.github.io/AgentsExampleZoo.jl/dev/), I'm redirected to the following website https://juliadynamics.github.io/AgentsExampleZoo.jl/dev/@ref 
and I get a 404 error. 
Maybe due to predator_prey.jl file missing from docs/examples?

Thanks

**Comment by Datseris** [comment]
Hi, it's because the example is now in the main Agents.jl documentation, https://juliadynamics.github.io/Agents.jl/dev/examples/predator_prey/  , not in the example zoo. A simple PR should change the link to the main docs!
