### ISSUE TITLE
Release the package in the general registry

### ISSUE THREAD

**Issue by ameligrana** [JuliaDynamics/AgentsExampleZoo.jl#29]
can you do so please @Datseris?

So that we can solve https://github.com/JuliaDynamics/Agents.jl/pull/939 :-)

I guess the fact that docs are not building is not a big problem because already happened with previous commits, even if we should really try to solve this after v6 is released

**Comment by Datseris** [comment]
@Tortar have you done this? It is as simple as going into `juliahub.com` and giving the package url in the "register package" button. I can do it if you haven't do it yet.

**Comment by ameligrana** [comment]
I'm releasing it but unfortunately in its current form `AgentsExampleZoo` depends on a version of `Agents` still unrelased (v6) but I overcame the problem by releasing a version which is okay for registrator because specifies Agents v5 but we need to merge https://github.com/JuliaDynamics/Agents.jl/pull/955 in Agents.jl because the release version will be incompatible with v6

pr: https://github.com/JuliaRegistries/General/pull/98859

**Comment by Datseris** [comment]
That's not a problem. We only release this _after_ v5 of Agents.jl is tagged. In the docs of Agents.jl, we can simply explicitly add the `main` branch of this repo, and not add it via the General Registry.

**Comment by ameligrana** [comment]
exactly what I did :+1:
