### ISSUE TITLE
Maze solver and mountain runners shows no video

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/AgentsExampleZoo.jl#6]
https://juliadynamics.github.io/AgentsExampleZoo.jl/dev/examples/maze/

https://juliadynamics.github.io/AgentsExampleZoo.jl/dev/examples/runners/

@AayushSabharwal maybe you can take a look for this one?

**Comment by AayushSabharwal** [comment]
Looks like it's just missing `FileIO` as a dependency
